# Generated by Django 3.2 on 2022-08-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pusher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app_secret_token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
